### ISSUE TITLE
GeoipCountry crashes the server

### ISSUE THREAD

**Issue by Septembers** [Accelerator74/GeoIP2#4]
Hello
I have a plugin that uses
GeoipCountry(this.m_szIP, this.m_szCountry, 32), and my server crashes when a player connects to the server
accelerator dump https://throttle.zizt.ru/pp6bfoxyewoa

there are no problems on the original version of geoip.
what is the problem?

**Comment by Accelerator74** [comment]
Compiled the plugin with a new .inc file?
Сan you show the plugin with the full code and give an which the IP causes crashes.

**Comment by Septembers** [comment]
Compiled with old inc.
The plugin is private, you need to request permission from the plugin developer.

**Comment by IIEnt** [comment]
Part of the code from the plugin
```c
public void OnClientPutInServer(int iClient)
{
	if(IsFailClient(iClient))
		return;

	pPlayer[iClient].RegisterClient(iClient);

 	// any code...
}

bool IsFailClient(int iClient)
{
	return IsFakeClient(iClient) || IsClientSourceTV(iClient);
}

method void RegisterClient(int iClient)
{
	this.m_iConTime = GetTime();
	
	if(!GetClientAuthId(iClient, AuthId_Engine, this.m_szAuth, 32))
	{
		this.m_iConTime = 0;
		return;
	}

	char szBuffer[64];
	GetClientName(iClient, szBuffer, sizeof(szBuffer));
	dBase.Escape(szBuffer, this.m_szName, MAX_NAME_LENGTH);

	GetClientIP(iClient, this.m_szIP, 32);
	GeoipCountry(this.m_szIP, this.m_szCountry, 32)

	if(!this.m_szCountry[0])
		this.m_szCountry = "Russian Federation";
}
```

**Comment by Accelerator74** [comment]
Recompile plugin with updated geoip.inc file from geoip2.

**Comment by Septembers** [comment]
thx, i recompile
